# Generated by Django 5.2.5 on 2025-08-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'Can view books'), ('can_create', 'Can create books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books'))},
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
    ]
